import { Donor } from '../types';

export const mockDonors: Donor[] = [
  { id: 'd1',  fullName: 'Rahul Sharma',    phoneNumber: '+91 98765 43210', bloodGroup: 'A+',  city: 'Jaipur', area: 'Malviya Nagar',    distance: 1.2, isAvailable: true,  isVerified: true,  totalDonations: 8,  lastDonation: '10 Jan 2024', gender: 'Male',   dateOfBirth: '12 May 1995' },
  { id: 'd2',  fullName: 'Vikram Singh',    phoneNumber: '+91 97654 32109', bloodGroup: 'B+',  city: 'Jaipur', area: 'Vaishali Nagar',   distance: 2.1, isAvailable: true,  isVerified: true,  totalDonations: 5,  lastDonation: '22 Dec 2023', gender: 'Male',   dateOfBirth: '05 Aug 1992' },
  { id: 'd3',  fullName: 'Amit Kumar',      phoneNumber: '+91 96543 21098', bloodGroup: 'O+',  city: 'Jaipur', area: 'Mansarovar',       distance: 2.8, isAvailable: true,  isVerified: true,  totalDonations: 12, lastDonation: '15 Nov 2023', gender: 'Male',   dateOfBirth: '18 Mar 1990' },
  { id: 'd4',  fullName: 'Sagar Patel',     phoneNumber: '+91 95432 10987', bloodGroup: 'AB+', city: 'Jaipur', area: 'C-Scheme',         distance: 3.2, isAvailable: false, isVerified: true,  totalDonations: 3,  lastDonation: '08 Oct 2023', gender: 'Male',   dateOfBirth: '25 Jul 1998' },
  { id: 'd5',  fullName: 'Neha Gupta',      phoneNumber: '+91 94321 09876', bloodGroup: 'A-',  city: 'Jaipur', area: 'Raja Park',        distance: 4.0, isAvailable: true,  isVerified: true,  totalDonations: 6,  lastDonation: '30 Sep 2023', gender: 'Female', dateOfBirth: '14 Feb 1994' },
  { id: 'd6',  fullName: 'Priya Mehta',     phoneNumber: '+91 93210 98765', bloodGroup: 'B-',  city: 'Jaipur', area: 'Shyam Nagar',     distance: 1.5, isAvailable: true,  isVerified: false, totalDonations: 2,  lastDonation: '12 Aug 2023', gender: 'Female', dateOfBirth: '03 Nov 1996' },
  { id: 'd7',  fullName: 'Rajesh Gupta',    phoneNumber: '+91 92109 87654', bloodGroup: 'O-',  city: 'Jaipur', area: 'Vidhyadhar Nagar', distance: 3.5, isAvailable: true,  isVerified: true,  totalDonations: 10, lastDonation: '19 Jul 2023', gender: 'Male',   dateOfBirth: '29 Dec 1988' },
  { id: 'd8',  fullName: 'Ankit Verma',     phoneNumber: '+91 91098 76543', bloodGroup: 'A+',  city: 'Jaipur', area: 'Pratap Nagar',    distance: 2.4, isAvailable: true,  isVerified: true,  totalDonations: 4,  lastDonation: '05 Jun 2023', gender: 'Male',   dateOfBirth: '11 Apr 1997' },
  { id: 'd9',  fullName: 'Sunita Verma',    phoneNumber: '+91 90987 65432', bloodGroup: 'B+',  city: 'Jaipur', area: 'Jagatpura',       distance: 5.1, isAvailable: false, isVerified: true,  totalDonations: 7,  lastDonation: '28 May 2023', gender: 'Female', dateOfBirth: '22 Jun 1991' },
  { id: 'd10', fullName: 'Sunil Mehta',     phoneNumber: '+91 89876 54321', bloodGroup: 'AB-', city: 'Jaipur', area: 'Sanganer',        distance: 6.2, isAvailable: true,  isVerified: true,  totalDonations: 1,  lastDonation: '14 Apr 2023', gender: 'Male',   dateOfBirth: '07 Jan 2000' },
  { id: 'd11', fullName: 'Deepak Joshi',    phoneNumber: '+91 88765 43210', bloodGroup: 'O+',  city: 'Jaipur', area: 'Malviya Nagar',   distance: 1.8, isAvailable: true,  isVerified: true,  totalDonations: 9,  lastDonation: '01 Mar 2024', gender: 'Male',   dateOfBirth: '17 Sep 1989' },
  { id: 'd12', fullName: 'Ravi Kumar',      phoneNumber: '+91 87654 32109', bloodGroup: 'A+',  city: 'Jaipur', area: 'Vaishali Nagar',  distance: 2.6, isAvailable: true,  isVerified: true,  totalDonations: 15, lastDonation: '18 Feb 2024', gender: 'Male',   dateOfBirth: '23 Oct 1986' },
  { id: 'd13', fullName: 'Anjali Singh',    phoneNumber: '+91 86543 21098', bloodGroup: 'B+',  city: 'Jaipur', area: 'Mansarovar',      distance: 3.0, isAvailable: true,  isVerified: false, totalDonations: 2,  lastDonation: '09 Jan 2024', gender: 'Female', dateOfBirth: '06 May 1999' },
  { id: 'd14', fullName: 'Manish Yadav',    phoneNumber: '+91 85432 10987', bloodGroup: 'O+',  city: 'Jaipur', area: 'C-Scheme',        distance: 4.3, isAvailable: false, isVerified: true,  totalDonations: 6,  lastDonation: '25 Dec 2023', gender: 'Male',   dateOfBirth: '31 Aug 1993' },
  { id: 'd15', fullName: 'Kavita Yadav',    phoneNumber: '+91 84321 09876', bloodGroup: 'A-',  city: 'Jaipur', area: 'Raja Park',       distance: 1.9, isAvailable: true,  isVerified: true,  totalDonations: 4,  lastDonation: '07 Nov 2023', gender: 'Female', dateOfBirth: '15 Jan 1995' },
  { id: 'd16', fullName: 'Pradeep Singh',   phoneNumber: '+91 83210 98765', bloodGroup: 'B-',  city: 'Jaipur', area: 'Shyam Nagar',    distance: 2.7, isAvailable: true,  isVerified: true,  totalDonations: 8,  lastDonation: '20 Oct 2023', gender: 'Male',   dateOfBirth: '09 Mar 1987' },
  { id: 'd17', fullName: 'Meena Patel',     phoneNumber: '+91 82109 87654', bloodGroup: 'AB+', city: 'Jaipur', area: 'Vidhyadhar Nagar',distance: 4.8, isAvailable: true,  isVerified: true,  totalDonations: 3,  lastDonation: '14 Sep 2023', gender: 'Female', dateOfBirth: '27 Jul 2001' },
  { id: 'd18', fullName: 'Nitin Chauhan',   phoneNumber: '+91 81098 76543', bloodGroup: 'O-',  city: 'Jaipur', area: 'Pratap Nagar',   distance: 3.3, isAvailable: false, isVerified: true,  totalDonations: 11, lastDonation: '03 Aug 2023', gender: 'Male',   dateOfBirth: '19 Feb 1984' },
  { id: 'd19', fullName: 'Rohit Kapoor',    phoneNumber: '+91 80987 65432', bloodGroup: 'A+',  city: 'Jaipur', area: 'Jagatpura',      distance: 5.6, isAvailable: true,  isVerified: true,  totalDonations: 7,  lastDonation: '22 Jul 2023', gender: 'Male',   dateOfBirth: '08 Jun 1990' },
  { id: 'd20', fullName: 'Ajay Mishra',     phoneNumber: '+91 79876 54321', bloodGroup: 'B+',  city: 'Jaipur', area: 'Sanganer',       distance: 7.1, isAvailable: true,  isVerified: false, totalDonations: 1,  lastDonation: '10 Jun 2023', gender: 'Male',   dateOfBirth: '14 Nov 1998' },
  { id: 'd21', fullName: 'Sandeep Tiwari',  phoneNumber: '+91 78765 43210', bloodGroup: 'O+',  city: 'Jaipur', area: 'Malviya Nagar',  distance: 1.4, isAvailable: true,  isVerified: true,  totalDonations: 13, lastDonation: '05 Mar 2024', gender: 'Male',   dateOfBirth: '30 Apr 1985' },
  { id: 'd22', fullName: 'Rekha Kumar',     phoneNumber: '+91 77654 32109', bloodGroup: 'A+',  city: 'Jaipur', area: 'Vaishali Nagar', distance: 2.3, isAvailable: true,  isVerified: true,  totalDonations: 5,  lastDonation: '14 Feb 2024', gender: 'Female', dateOfBirth: '21 Aug 1993' },
  { id: 'd23', fullName: 'Harish Patel',    phoneNumber: '+91 76543 21098', bloodGroup: 'B+',  city: 'Jaipur', area: 'Mansarovar',     distance: 3.7, isAvailable: false, isVerified: true,  totalDonations: 6,  lastDonation: '27 Jan 2024', gender: 'Male',   dateOfBirth: '02 Dec 1991' },
  { id: 'd24', fullName: 'Nisha Agarwal',   phoneNumber: '+91 75432 10987', bloodGroup: 'AB+', city: 'Jaipur', area: 'C-Scheme',       distance: 4.1, isAvailable: true,  isVerified: true,  totalDonations: 2,  lastDonation: '11 Jan 2024', gender: 'Female', dateOfBirth: '17 Mar 2000' },
  { id: 'd25', fullName: 'Manoj Kumar',     phoneNumber: '+91 74321 09876', bloodGroup: 'O+',  city: 'Jaipur', area: 'Raja Park',      distance: 2.9, isAvailable: true,  isVerified: true,  totalDonations: 9,  lastDonation: '29 Dec 2023', gender: 'Male',   dateOfBirth: '05 Jul 1988' },
  { id: 'd26', fullName: 'Swati Jain',      phoneNumber: '+91 73210 98765', bloodGroup: 'A-',  city: 'Jaipur', area: 'Shyam Nagar',   distance: 1.7, isAvailable: true,  isVerified: true,  totalDonations: 4,  lastDonation: '16 Nov 2023', gender: 'Female', dateOfBirth: '11 Feb 1996' },
  { id: 'd27', fullName: 'Vinay Singh',     phoneNumber: '+91 72109 87654', bloodGroup: 'B-',  city: 'Jaipur', area: 'Vidhyadhar Nagar',distance: 3.9, isAvailable: true,  isVerified: false, totalDonations: 3, lastDonation: '01 Nov 2023', gender: 'Male',   dateOfBirth: '26 Sep 1994' },
  { id: 'd28', fullName: 'Gopal Das',       phoneNumber: '+91 71098 76543', bloodGroup: 'O-',  city: 'Jaipur', area: 'Pratap Nagar',  distance: 4.5, isAvailable: false, isVerified: true,  totalDonations: 16, lastDonation: '14 Oct 2023', gender: 'Male',   dateOfBirth: '08 Mar 1980' },
  { id: 'd29', fullName: 'Divya Mishra',    phoneNumber: '+91 70987 65432', bloodGroup: 'A+',  city: 'Jaipur', area: 'Jagatpura',     distance: 5.4, isAvailable: true,  isVerified: true,  totalDonations: 7,  lastDonation: '08 Sep 2023', gender: 'Female', dateOfBirth: '14 May 1997' },
  { id: 'd30', fullName: 'Ramesh Verma',    phoneNumber: '+91 69876 54321', bloodGroup: 'B+',  city: 'Jaipur', area: 'Sanganer',       distance: 6.8, isAvailable: true,  isVerified: true,  totalDonations: 2,  lastDonation: '22 Aug 2023', gender: 'Male',   dateOfBirth: '19 Jun 1999' },
  { id: 'd31', fullName: 'Arun Gupta',      phoneNumber: '+91 68765 43210', bloodGroup: 'AB-', city: 'Jaipur', area: 'Malviya Nagar',  distance: 1.6, isAvailable: true,  isVerified: true,  totalDonations: 10, lastDonation: '19 Mar 2024', gender: 'Male',   dateOfBirth: '03 Jan 1987' },
  { id: 'd32', fullName: 'Pratibha Singh',  phoneNumber: '+91 67654 32109', bloodGroup: 'O+',  city: 'Jaipur', area: 'Vaishali Nagar', distance: 2.2, isAvailable: true,  isVerified: true,  totalDonations: 5,  lastDonation: '02 Mar 2024', gender: 'Female', dateOfBirth: '30 Oct 1992' },
  { id: 'd33', fullName: 'Naveen Sharma',   phoneNumber: '+91 66543 21098', bloodGroup: 'A+',  city: 'Jaipur', area: 'Mansarovar',     distance: 3.4, isAvailable: false, isVerified: true,  totalDonations: 8,  lastDonation: '15 Feb 2024', gender: 'Male',   dateOfBirth: '16 Jul 1989' },
  { id: 'd34', fullName: 'Asha Chauhan',    phoneNumber: '+91 65432 10987', bloodGroup: 'B+',  city: 'Jaipur', area: 'C-Scheme',       distance: 4.6, isAvailable: true,  isVerified: false, totalDonations: 1,  lastDonation: '01 Feb 2024', gender: 'Female', dateOfBirth: '24 Apr 2001' },
  { id: 'd35', fullName: 'Suresh Nair',     phoneNumber: '+91 64321 09876', bloodGroup: 'O+',  city: 'Jaipur', area: 'Raja Park',      distance: 3.1, isAvailable: true,  isVerified: true,  totalDonations: 12, lastDonation: '20 Jan 2024', gender: 'Male',   dateOfBirth: '12 Nov 1985' },
  { id: 'd36', fullName: 'Kiran Kumar',     phoneNumber: '+91 63210 98765', bloodGroup: 'A-',  city: 'Jaipur', area: 'Shyam Nagar',    distance: 2.0, isAvailable: true,  isVerified: true,  totalDonations: 6,  lastDonation: '08 Jan 2024', gender: 'Male',   dateOfBirth: '07 Aug 1993' },
  { id: 'd37', fullName: 'Mohan Lal',       phoneNumber: '+91 62109 87654', bloodGroup: 'B-',  city: 'Jaipur', area: 'Vidhyadhar Nagar',distance: 4.0, isAvailable: false, isVerified: true,  totalDonations: 9,  lastDonation: '22 Dec 2023', gender: 'Male',   dateOfBirth: '25 Feb 1983' },
  { id: 'd38', fullName: 'Sudha Rao',       phoneNumber: '+91 61098 76543', bloodGroup: 'AB+', city: 'Jaipur', area: 'Pratap Nagar',   distance: 5.2, isAvailable: true,  isVerified: true,  totalDonations: 3,  lastDonation: '10 Dec 2023', gender: 'Female', dateOfBirth: '19 Sep 1995' },
  { id: 'd39', fullName: 'Anil Mehta',      phoneNumber: '+91 60987 65432', bloodGroup: 'O+',  city: 'Jaipur', area: 'Jagatpura',      distance: 5.8, isAvailable: true,  isVerified: true,  totalDonations: 14, lastDonation: '28 Nov 2023', gender: 'Male',   dateOfBirth: '01 May 1981' },
  { id: 'd40', fullName: 'Vijay Prasad',    phoneNumber: '+91 59876 54321', bloodGroup: 'A+',  city: 'Jaipur', area: 'Sanganer',       distance: 7.5, isAvailable: true,  isVerified: false, totalDonations: 2,  lastDonation: '15 Nov 2023', gender: 'Male',   dateOfBirth: '09 Dec 1997' },
  { id: 'd41', fullName: 'Sanjay Yadav',    phoneNumber: '+91 58765 43210', bloodGroup: 'B+',  city: 'Jaipur', area: 'Malviya Nagar',  distance: 1.3, isAvailable: true,  isVerified: true,  totalDonations: 11, lastDonation: '25 Mar 2024', gender: 'Male',   dateOfBirth: '15 Jun 1986' },
  { id: 'd42', fullName: 'Kamla Devi',      phoneNumber: '+91 57654 32109', bloodGroup: 'O-',  city: 'Jaipur', area: 'Vaishali Nagar', distance: 2.5, isAvailable: true,  isVerified: true,  totalDonations: 4,  lastDonation: '12 Mar 2024', gender: 'Female', dateOfBirth: '28 Jan 1990' },
  { id: 'd43', fullName: 'Dinesh Kumar',    phoneNumber: '+91 56543 21098', bloodGroup: 'A+',  city: 'Jaipur', area: 'Mansarovar',     distance: 3.6, isAvailable: false, isVerified: true,  totalDonations: 7,  lastDonation: '01 Mar 2024', gender: 'Male',   dateOfBirth: '04 Oct 1991' },
  { id: 'd44', fullName: 'Tarun Singh',     phoneNumber: '+91 55432 10987', bloodGroup: 'AB-', city: 'Jaipur', area: 'C-Scheme',       distance: 4.4, isAvailable: true,  isVerified: true,  totalDonations: 5,  lastDonation: '18 Feb 2024', gender: 'Male',   dateOfBirth: '22 Apr 1994' },
  { id: 'd45', fullName: 'Pooja Sharma',    phoneNumber: '+91 54321 09876', bloodGroup: 'B+',  city: 'Jaipur', area: 'Raja Park',      distance: 2.8, isAvailable: true,  isVerified: true,  totalDonations: 6,  lastDonation: '05 Feb 2024', gender: 'Female', dateOfBirth: '11 Jun 1995' },
  { id: 'd46', fullName: 'Giridhar Rao',    phoneNumber: '+91 53210 98765', bloodGroup: 'O+',  city: 'Jaipur', area: 'Shyam Nagar',   distance: 3.2, isAvailable: true,  isVerified: true,  totalDonations: 8,  lastDonation: '25 Jan 2024', gender: 'Male',   dateOfBirth: '17 Mar 1988' },
  { id: 'd47', fullName: 'Rashmi Gupta',    phoneNumber: '+91 52109 87654', bloodGroup: 'A-',  city: 'Jaipur', area: 'Vidhyadhar Nagar',distance: 4.7, isAvailable: false, isVerified: false, totalDonations: 2, lastDonation: '14 Jan 2024', gender: 'Female', dateOfBirth: '03 Nov 1998' },
  { id: 'd48', fullName: 'Chetan Bhatt',    phoneNumber: '+91 51098 76543', bloodGroup: 'B-',  city: 'Jaipur', area: 'Pratap Nagar',  distance: 5.0, isAvailable: true,  isVerified: true,  totalDonations: 9,  lastDonation: '03 Jan 2024', gender: 'Male',   dateOfBirth: '26 Aug 1987' },
  { id: 'd49', fullName: 'Lalita Sharma',   phoneNumber: '+91 50987 65432', bloodGroup: 'AB+', city: 'Jaipur', area: 'Jagatpura',     distance: 5.7, isAvailable: true,  isVerified: true,  totalDonations: 3,  lastDonation: '20 Dec 2023', gender: 'Female', dateOfBirth: '09 Jul 1996' },
  { id: 'd50', fullName: 'Bharat Kapoor',   phoneNumber: '+91 49876 54321', bloodGroup: 'O+',  city: 'Jaipur', area: 'Sanganer',      distance: 8.0, isAvailable: true,  isVerified: true,  totalDonations: 17, lastDonation: '08 Dec 2023', gender: 'Male',   dateOfBirth: '12 Feb 1979' },
];

export const getAvailableDonors = () => mockDonors.filter(d => d.isAvailable);

export const getDonorsByBloodGroup = (bg: string) =>
  mockDonors.filter(d => d.bloodGroup === bg && d.isAvailable);

export const getNearbyDonors = (limit = 5) =>
  mockDonors
    .filter(d => d.isAvailable)
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit);
