import { BloodRequest } from '../types';

export const mockRequests: BloodRequest[] = [
  { id: 'r1',  requestId: 'REQ123456', patientName: 'Rohit Verma',    hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 2, urgency: 'Urgent', requiredBy: 'Today, 6:00 PM',   contactPerson: 'Amit Verma',    contactPhone: '+91 98765 43211', status: 'Approved',  distance: 1.2, createdAt: '2024-01-10', postedAgo: '2 min ago',   receiverId: 'rc1', matchingDonors: ['d1','d8','d12','d22','d29'] },
  { id: 'r2',  requestId: 'REQ123457', patientName: 'Sunita Devi',    hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 1, urgency: 'High',   requiredBy: 'Today, 8:00 PM',   contactPerson: 'Rakesh Kumar',  contactPhone: '+91 97654 32110', status: 'Pending',   distance: 2.8, createdAt: '2024-01-10', postedAgo: '10 min ago',  receiverId: 'rc2', matchingDonors: ['d2','d9','d13','d23','d45'] },
  { id: 'r3',  requestId: 'REQ123458', patientName: 'Mahesh Gupta',   hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 10:00 AM',contactPerson: 'Seema Gupta',   contactPhone: '+91 96543 21099', status: 'Pending',   distance: 3.1, createdAt: '2024-01-10', postedAgo: '20 min ago',  receiverId: 'rc3', matchingDonors: ['d3','d11','d14','d25','d32'] },
  { id: 'r4',  requestId: 'REQ123459', patientName: 'Ratan Singh',    hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'AB+', unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 4:00 PM',   contactPerson: 'Mohan Singh',   contactPhone: '+91 95432 10988', status: 'Pending',   distance: 4.5, createdAt: '2024-01-10', postedAgo: '35 min ago',  receiverId: 'rc4', matchingDonors: ['d4','d17','d24','d38','d49'] },
  { id: 'r5',  requestId: 'REQ123460', patientName: 'Geeta Sharma',   hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'A-',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 2 days',        contactPerson: 'Suresh Sharma', contactPhone: '+91 94321 09877', status: 'Pending',   distance: 5.2, createdAt: '2024-01-09', postedAgo: '1 hr ago',    receiverId: 'rc5', matchingDonors: ['d5','d15','d26','d36','d47'] },
  { id: 'r6',  requestId: 'REQ123461', patientName: 'Vijay Kumar',    hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'B-',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Today, 9:00 PM',   contactPerson: 'Kavita Kumar',  contactPhone: '+91 93210 98766', status: 'Pending',   distance: 3.8, createdAt: '2024-01-10', postedAgo: '45 min ago',  receiverId: 'rc6', matchingDonors: ['d6','d16','d27','d37','d48'] },
  { id: 'r7',  requestId: 'REQ123462', patientName: 'Anita Patel',    hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'O-',  unitsNeeded: 1, urgency: 'Medium', requiredBy: 'Tomorrow, 2:00 PM', contactPerson: 'Ramesh Patel',  contactPhone: '+91 92109 87655', status: 'Approved',  distance: 6.1, createdAt: '2024-01-09', postedAgo: '2 hr ago',    receiverId: 'rc7', matchingDonors: ['d7','d18','d28','d42'] },
  { id: 'r8',  requestId: 'REQ123463', patientName: 'Dinesh Mehta',   hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 3:00 PM',   contactPerson: 'Priya Mehta',   contactPhone: '+91 91098 76544', status: 'Pending',   distance: 1.5, createdAt: '2024-01-10', postedAgo: '5 min ago',   receiverId: 'rc8', matchingDonors: ['d1','d8','d12','d22','d33'] },
  { id: 'r9',  requestId: 'REQ123464', patientName: 'Sarla Devi',     hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 8:00 AM', contactPerson: 'Vikram Sharma', contactPhone: '+91 90987 65433', status: 'Pending',   distance: 2.4, createdAt: '2024-01-10', postedAgo: '18 min ago',  receiverId: 'rc9', matchingDonors: ['d2','d9','d13','d23','d41'] },
  { id: 'r10', requestId: 'REQ123465', patientName: 'Kamal Kishore',  hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'AB-', unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 3 days',        contactPerson: 'Suman Kishore', contactPhone: '+91 89876 54322', status: 'Completed', distance: 3.5, createdAt: '2024-01-08', postedAgo: '1 day ago',   receiverId: 'rc10',matchingDonors: ['d10','d31','d44'] },
  { id: 'r11', requestId: 'REQ123466', patientName: 'Bhavna Joshi',   hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 12:00 PM',contactPerson: 'Deepak Joshi',  contactPhone: '+91 88765 43211', status: 'Pending',   distance: 4.2, createdAt: '2024-01-10', postedAgo: '30 min ago',  receiverId: 'rc11',matchingDonors: ['d3','d11','d25','d32','d35'] },
  { id: 'r12', requestId: 'REQ123467', patientName: 'Govind Rao',     hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 1, urgency: 'Urgent', requiredBy: 'Today, 7:00 PM',   contactPerson: 'Asha Rao',      contactPhone: '+91 87654 32110', status: 'Approved',  distance: 2.0, createdAt: '2024-01-10', postedAgo: '8 min ago',   receiverId: 'rc12',matchingDonors: ['d1','d8','d19','d22','d29'] },
  { id: 'r13', requestId: 'REQ123468', patientName: 'Lata Sharma',    hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 4, urgency: 'Urgent', requiredBy: 'Today, 5:00 PM',   contactPerson: 'Rakesh Sharma', contactPhone: '+91 86543 21099', status: 'Pending',   distance: 3.3, createdAt: '2024-01-10', postedAgo: '12 min ago',  receiverId: 'rc13',matchingDonors: ['d2','d9','d13','d30','d41'] },
  { id: 'r14', requestId: 'REQ123469', patientName: 'Suresh Agarwal', hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 9:00 AM', contactPerson: 'Meena Agarwal', contactPhone: '+91 85432 10988', status: 'Pending',   distance: 5.8, createdAt: '2024-01-09', postedAgo: '3 hr ago',    receiverId: 'rc14',matchingDonors: ['d3','d11','d14','d25','d46'] },
  { id: 'r15', requestId: 'REQ123470', patientName: 'Rekha Verma',    hospitalName: 'Manipal Hospital', location: 'Jaipur, Rajasthan', bloodGroup: 'A-',  unitsNeeded: 1, urgency: 'Medium', requiredBy: 'In 2 days',        contactPerson: 'Anand Verma',   contactPhone: '+91 84321 09877', status: 'Pending',   distance: 4.7, createdAt: '2024-01-09', postedAgo: '5 hr ago',    receiverId: 'rc15',matchingDonors: ['d5','d15','d36','d47'] },
  { id: 'r16', requestId: 'REQ123471', patientName: 'Harish Chand',   hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'AB+', unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 11:00 AM',contactPerson: 'Sunita Chand',  contactPhone: '+91 83210 98766', status: 'Pending',   distance: 1.8, createdAt: '2024-01-10', postedAgo: '25 min ago',  receiverId: 'rc16',matchingDonors: ['d4','d17','d24','d38'] },
  { id: 'r17', requestId: 'REQ123472', patientName: 'Nirmala Devi',   hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'B-',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 4 days',        contactPerson: 'Sunil Devi',    contactPhone: '+91 82109 87655', status: 'Pending',   distance: 3.0, createdAt: '2024-01-08', postedAgo: '2 days ago',  receiverId: 'rc17',matchingDonors: ['d6','d16','d27','d37'] },
  { id: 'r18', requestId: 'REQ123473', patientName: 'Prakash Singh',  hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'O-',  unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 2:00 PM',   contactPerson: 'Meera Singh',   contactPhone: '+91 81098 76544', status: 'Pending',   distance: 2.6, createdAt: '2024-01-10', postedAgo: '3 min ago',   receiverId: 'rc18',matchingDonors: ['d7','d18','d28','d42'] },
  { id: 'r19', requestId: 'REQ123474', patientName: 'Shobha Kumari',  hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 3:00 PM', contactPerson: 'Mohan Kumar',   contactPhone: '+91 80987 65433', status: 'Pending',   distance: 4.9, createdAt: '2024-01-09', postedAgo: '4 hr ago',    receiverId: 'rc19',matchingDonors: ['d1','d8','d12','d29','d33'] },
  { id: 'r20', requestId: 'REQ123475', patientName: 'Tilak Raj',      hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 1, urgency: 'High',   requiredBy: 'Today, 10:00 PM',  contactPerson: 'Kamla Raj',     contactPhone: '+91 79876 54322', status: 'Completed', distance: 6.3, createdAt: '2024-01-07', postedAgo: '3 days ago',  receiverId: 'rc20',matchingDonors: ['d2','d23','d41','d45'] },
  { id: 'r21', requestId: 'REQ123476', patientName: 'Bimla Sharma',   hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'Urgent', requiredBy: 'Today, 1:00 PM',   contactPerson: 'Ramesh Sharma', contactPhone: '+91 78765 43211', status: 'Pending',   distance: 2.2, createdAt: '2024-01-10', postedAgo: '7 min ago',   receiverId: 'rc1', matchingDonors: ['d3','d11','d21','d32','d46'] },
  { id: 'r22', requestId: 'REQ123477', patientName: 'Chandra Bhan',   hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'AB-', unitsNeeded: 1, urgency: 'Medium', requiredBy: 'In 2 days',        contactPerson: 'Sita Bhan',     contactPhone: '+91 77654 32110', status: 'Pending',   distance: 5.5, createdAt: '2024-01-09', postedAgo: '6 hr ago',    receiverId: 'rc2', matchingDonors: ['d10','d31','d44'] },
  { id: 'r23', requestId: 'REQ123478', patientName: 'Dhanraj Patel',  hospitalName: 'Manipal Hospital', location: 'Jaipur, Rajasthan', bloodGroup: 'A-',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 7:00 AM', contactPerson: 'Pushpa Patel',  contactPhone: '+91 76543 21099', status: 'Pending',   distance: 4.0, createdAt: '2024-01-10', postedAgo: '40 min ago',  receiverId: 'rc3', matchingDonors: ['d5','d15','d26','d36'] },
  { id: 'r24', requestId: 'REQ123479', patientName: 'Ekta Verma',     hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 11:00 PM',  contactPerson: 'Ravi Verma',    contactPhone: '+91 75432 10988', status: 'Pending',   distance: 1.6, createdAt: '2024-01-10', postedAgo: '15 min ago',  receiverId: 'rc4', matchingDonors: ['d2','d9','d23','d34','d41'] },
  { id: 'r25', requestId: 'REQ123480', patientName: 'Fatima Begum',   hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 5 days',        contactPerson: 'Ahmed Khan',    contactPhone: '+91 74321 09877', status: 'Pending',   distance: 3.7, createdAt: '2024-01-08', postedAgo: '2 days ago',  receiverId: 'rc5', matchingDonors: ['d3','d11','d25','d39','d50'] },
  { id: 'r26', requestId: 'REQ123481', patientName: 'Gita Rani',      hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'AB+', unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 5:00 PM', contactPerson: 'Shyam Rani',    contactPhone: '+91 73210 98766', status: 'Approved',  distance: 2.9, createdAt: '2024-01-10', postedAgo: '55 min ago',  receiverId: 'rc6', matchingDonors: ['d4','d17','d38','d49'] },
  { id: 'r27', requestId: 'REQ123482', patientName: 'Hemant Kumar',   hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 4:00 PM', contactPerson: 'Jyoti Kumar',   contactPhone: '+91 72109 87655', status: 'Pending',   distance: 4.3, createdAt: '2024-01-10', postedAgo: '1 hr ago',    receiverId: 'rc7', matchingDonors: ['d1','d8','d12','d22','d43'] },
  { id: 'r28', requestId: 'REQ123483', patientName: 'Indra Devi',     hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'B-',  unitsNeeded: 1, urgency: 'Urgent', requiredBy: 'Today, 8:00 PM',   contactPerson: 'Kapil Dev',     contactPhone: '+91 71098 76544', status: 'Pending',   distance: 3.4, createdAt: '2024-01-10', postedAgo: '22 min ago',  receiverId: 'rc8', matchingDonors: ['d6','d16','d27','d48'] },
  { id: 'r29', requestId: 'REQ123484', patientName: 'Jagdish Prasad', hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'O-',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Today, 11:00 PM',  contactPerson: 'Lakshmi Prasad',contactPhone: '+91 70987 65433', status: 'Pending',   distance: 5.3, createdAt: '2024-01-10', postedAgo: '50 min ago',  receiverId: 'rc9', matchingDonors: ['d7','d18','d28','d42'] },
  { id: 'r30', requestId: 'REQ123485', patientName: 'Kamini Sharma',  hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 3 days',        contactPerson: 'Nand Sharma',   contactPhone: '+91 69876 54322', status: 'Completed', distance: 7.0, createdAt: '2024-01-06', postedAgo: '4 days ago',  receiverId: 'rc10',matchingDonors: ['d1','d12','d33','d40'] },
  { id: 'r31', requestId: 'REQ123486', patientName: 'Lalit Mohan',    hospitalName: 'Manipal Hospital', location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 1:00 PM', contactPerson: 'Maya Mohan',    contactPhone: '+91 68765 43211', status: 'Pending',   distance: 4.6, createdAt: '2024-01-09', postedAgo: '7 hr ago',    receiverId: 'rc11',matchingDonors: ['d2','d9','d13','d30','d45'] },
  { id: 'r32', requestId: 'REQ123487', patientName: 'Manorama Devi',  hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 12:00 PM',  contactPerson: 'Naresh Kumar',  contactPhone: '+91 67654 32110', status: 'Pending',   distance: 1.9, createdAt: '2024-01-10', postedAgo: '6 min ago',   receiverId: 'rc12',matchingDonors: ['d3','d11','d21','d32','d35'] },
  { id: 'r33', requestId: 'REQ123488', patientName: 'Naval Kishore',  hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'AB+', unitsNeeded: 1, urgency: 'High',   requiredBy: 'Tomorrow, 6:00 AM', contactPerson: 'Om Prakash',    contactPhone: '+91 66543 21099', status: 'Pending',   distance: 3.2, createdAt: '2024-01-10', postedAgo: '35 min ago',  receiverId: 'rc13',matchingDonors: ['d4','d17','d24','d38','d49'] },
  { id: 'r34', requestId: 'REQ123489', patientName: 'Om Vati',        hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'A-',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'In 2 days',        contactPerson: 'Prem Lal',      contactPhone: '+91 65432 10988', status: 'Pending',   distance: 5.0, createdAt: '2024-01-09', postedAgo: '8 hr ago',    receiverId: 'rc14',matchingDonors: ['d5','d15','d26','d47'] },
  { id: 'r35', requestId: 'REQ123490', patientName: 'Pushpa Singh',   hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'B-',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 4 days',        contactPerson: 'Qasim Ali',     contactPhone: '+91 64321 09877', status: 'Pending',   distance: 3.8, createdAt: '2024-01-08', postedAgo: '3 days ago',  receiverId: 'rc15',matchingDonors: ['d6','d16','d27','d37','d48'] },
  { id: 'r36', requestId: 'REQ123491', patientName: 'Radha Krishnan', hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'O-',  unitsNeeded: 2, urgency: 'Urgent', requiredBy: 'Today, 5:00 PM',   contactPerson: 'Rani Devi',     contactPhone: '+91 63210 98766', status: 'Approved',  distance: 2.5, createdAt: '2024-01-10', postedAgo: '9 min ago',   receiverId: 'rc16',matchingDonors: ['d7','d28','d42'] },
  { id: 'r37', requestId: 'REQ123492', patientName: 'Savita Kumari',  hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Today, 9:00 PM',   contactPerson: 'Satish Kumar',  contactPhone: '+91 62109 87655', status: 'Pending',   distance: 4.1, createdAt: '2024-01-10', postedAgo: '48 min ago',  receiverId: 'rc17',matchingDonors: ['d1','d8','d12','d22','d43'] },
  { id: 'r38', requestId: 'REQ123493', patientName: 'Tara Chand',     hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 3:30 PM',   contactPerson: 'Uma Chand',     contactPhone: '+91 61098 76544', status: 'Pending',   distance: 1.4, createdAt: '2024-01-10', postedAgo: '4 min ago',   receiverId: 'rc18',matchingDonors: ['d2','d9','d30','d41','d45'] },
  { id: 'r39', requestId: 'REQ123494', patientName: 'Usha Devi',      hospitalName: 'Manipal Hospital', location: 'Jaipur, Rajasthan', bloodGroup: 'AB-', unitsNeeded: 1, urgency: 'Medium', requiredBy: 'Tomorrow, 11:00 AM',contactPerson: 'Vijay Kumar',   contactPhone: '+91 60987 65433', status: 'Pending',   distance: 5.6, createdAt: '2024-01-09', postedAgo: '9 hr ago',    receiverId: 'rc19',matchingDonors: ['d10','d31','d44'] },
  { id: 'r40', requestId: 'REQ123495', patientName: 'Vasudha Sharma', hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 8:00 AM', contactPerson: 'Waman Lal',     contactPhone: '+91 59876 54322', status: 'Completed', distance: 2.1, createdAt: '2024-01-05', postedAgo: '5 days ago',  receiverId: 'rc20',matchingDonors: ['d3','d11','d14','d32','d50'] },
  { id: 'r41', requestId: 'REQ123496', patientName: 'Yamini Gupta',   hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 3 days',        contactPerson: 'Yash Gupta',    contactPhone: '+91 58765 43211', status: 'Pending',   distance: 3.6, createdAt: '2024-01-08', postedAgo: '2 days ago',  receiverId: 'rc1', matchingDonors: ['d1','d12','d22','d40'] },
  { id: 'r42', requestId: 'REQ123497', patientName: 'Zainab Khatoon', hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'B-',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Tomorrow, 4:00 AM', contactPerson: 'Zafar Khan',    contactPhone: '+91 57654 32110', status: 'Pending',   distance: 4.7, createdAt: '2024-01-10', postedAgo: '1.5 hr ago',  receiverId: 'rc2', matchingDonors: ['d6','d16','d27','d48'] },
  { id: 'r43', requestId: 'REQ123498', patientName: 'Aarav Sharma',   hospitalName: 'Fortis Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 2, urgency: 'Medium', requiredBy: 'Tomorrow, 2:00 PM', contactPerson: 'Aakash Sharma', contactPhone: '+91 56543 21099', status: 'Pending',   distance: 5.1, createdAt: '2024-01-09', postedAgo: '10 hr ago',   receiverId: 'rc3', matchingDonors: ['d3','d11','d21','d32','d46'] },
  { id: 'r44', requestId: 'REQ123499', patientName: 'Bhumi Patel',    hospitalName: 'Apollo Hospital',  location: 'Jaipur, Rajasthan', bloodGroup: 'AB+', unitsNeeded: 3, urgency: 'Urgent', requiredBy: 'Today, 4:30 PM',   contactPerson: 'Chirag Patel',  contactPhone: '+91 55432 10988', status: 'Pending',   distance: 2.3, createdAt: '2024-01-10', postedAgo: '11 min ago',  receiverId: 'rc4', matchingDonors: ['d4','d17','d24','d49'] },
  { id: 'r45', requestId: 'REQ123500', patientName: 'Chetan Kumar',   hospitalName: 'AIIMS Jaipur',     location: 'Jaipur, Rajasthan', bloodGroup: 'A-',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 5 days',        contactPerson: 'Disha Kumar',   contactPhone: '+91 54321 09877', status: 'Pending',   distance: 6.7, createdAt: '2024-01-07', postedAgo: '3 days ago',  receiverId: 'rc5', matchingDonors: ['d5','d15','d36'] },
  { id: 'r46', requestId: 'REQ123501', patientName: 'Devika Rathore', hospitalName: 'Narayana Hospital',location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 2, urgency: 'High',   requiredBy: 'Today, 8:30 PM',   contactPerson: 'Eklavya Rao',   contactPhone: '+91 53210 98766', status: 'Pending',   distance: 3.9, createdAt: '2024-01-10', postedAgo: '28 min ago',  receiverId: 'rc6', matchingDonors: ['d2','d9','d13','d23','d41'] },
  { id: 'r47', requestId: 'REQ123502', patientName: 'Farida Bano',    hospitalName: 'Manipal Hospital', location: 'Jaipur, Rajasthan', bloodGroup: 'O-',  unitsNeeded: 1, urgency: 'Medium', requiredBy: 'Tomorrow, 6:00 PM', contactPerson: 'Faisal Khan',   contactPhone: '+91 52109 87655', status: 'Approved',  distance: 4.8, createdAt: '2024-01-09', postedAgo: '12 hr ago',   receiverId: 'rc7', matchingDonors: ['d7','d18','d28'] },
  { id: 'r48', requestId: 'REQ123503', patientName: 'Gagan Sharma',   hospitalName: 'SMS Hospital',     location: 'Jaipur, Rajasthan', bloodGroup: 'A+',  unitsNeeded: 2, urgency: 'Urgent', requiredBy: 'Today, 2:30 PM',   contactPerson: 'Hema Sharma',   contactPhone: '+91 51098 76544', status: 'Pending',   distance: 1.7, createdAt: '2024-01-10', postedAgo: '14 min ago',  receiverId: 'rc8', matchingDonors: ['d1','d8','d12','d22','d33'] },
  { id: 'r49', requestId: 'REQ123504', patientName: 'Himani Verma',   hospitalName: 'Noble Hospital',   location: 'Jaipur, Rajasthan', bloodGroup: 'B+',  unitsNeeded: 3, urgency: 'High',   requiredBy: 'Tomorrow, 7:00 PM', contactPerson: 'Ishaan Verma',  contactPhone: '+91 50987 65433', status: 'Pending',   distance: 2.7, createdAt: '2024-01-10', postedAgo: '42 min ago',  receiverId: 'rc9', matchingDonors: ['d2','d9','d23','d34','d45'] },
  { id: 'r50', requestId: 'REQ123505', patientName: 'Ishita Gupta',   hospitalName: 'City Hospital',    location: 'Jaipur, Rajasthan', bloodGroup: 'O+',  unitsNeeded: 1, urgency: 'Low',    requiredBy: 'In 4 days',        contactPerson: 'Jai Gupta',     contactPhone: '+91 49876 54322', status: 'Pending',   distance: 5.9, createdAt: '2024-01-08', postedAgo: '2 days ago',  receiverId: 'rc10',matchingDonors: ['d3','d11','d14','d25','d50'] },
];

export const getNearbyRequests = (limit = 10) =>
  mockRequests
    .filter(r => r.status === 'Pending' || r.status === 'Approved')
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit);

export const getUrgentRequests = () =>
  mockRequests.filter(r => r.urgency === 'Urgent' && r.status === 'Pending');

export const getRequestById = (id: string) =>
  mockRequests.find(r => r.id === id || r.requestId === id);
